// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqpfwdxfmemwegkrxkre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxcGZ3ZHhmbWVtd2Vna3J4a3JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzMTg3MTgsImV4cCI6MjA3NTg5NDcxOH0.WthxYw9lfNJI2vlb3kD-2_NuRzV1zTiMV6C8s726o7s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});